
Spring:
  application:
    name: provider01
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springbootdb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 192.168.80.101
    port: 6379


mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  #使用IP注册
  instance:
    prefer-ip-address: true